---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.20.0"
  ingress:
    istio:
      enabled: false
  config:
    network:
      ingress-class: gateway-api.ingress.networking.knative.dev
    autoscaler:
      stable-window: "10s"
      container-concurrency-target-default: "10"
