apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: knative-serving.cncf.demo
spec:
  namespace: workload
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: knative-serving.cncf.demo
  namespace: workload
spec:
  ref:
    name: cncf-server
    kind: Service
    apiVersion: serving.knative.dev/v1
